vim.cmd("colorscheme carbonfox")
-- vim.cmd("colorscheme nightfox")
-- vim.cmd("colorscheme duskfox")
-- vim.cmd("colorscheme nordfox")
-- vim.cmd("colorscheme terafox")
-- vim.cmd("colorscheme tokyodark")
